### ISSUE TITLE
Achievements for 1.18

### ISSUE THREAD

**Issue by EstebanJean-PRO** [ochotonida/some-assembly-required#20]
Hey,
I compared 1.16 translation files with 1.18's and noticed the BLT achievement was missing in the newer version. I'm guessing it's on purpose, so my question is:
What changes regarding achievements have you planned? Anything new and/or anything less?

**Comment by ochotonida** [comment]
I don't have any more changes planned for the achievements, apart from what's already there (FYI, the 1.18 update is already available). There's always a possibility I might add more achievements in the future, but I don't have any concrete plans right now.

The BLT achievements was removed for 2 reasons:
- I decided to cut a lot of content when porting to 1.18, partly to remove the content overlap with Farmer's Delight, and partly just to remove unnecessary clutter. I removed lettuce because Farmer's Delight already adds cabbage and it's close enough.
- I might make the FD dependency optional in the future, and just let modpack makers implement any missing recipes that normally require FD. In that case the advancement could be unobtainable though, since all the ingredients for a BLT require Farmer's Delight.
