### ISSUE TITLE
JEI does not render

### ISSUE THREAD

**Issue by WenXin20** [ochotonida/some-assembly-required#21]
```
Minecraft v1.18.1
Forge v39.0.88
Farmer's Delight v1.0.3
Some Assembly Required v2.0.0
JEI v9.4.1.110
```

After installing Some Assembly Required, I noticed that JEI would not load. After removing SAR, JEI started working again. I'm not sure what is causing this error when connecting to my server.
[Latest.log](https://gist.github.com/WenXin20/ce3c114c913b93af199290cd0716f339#file-latest-log-L2266)

**Comment by EstebanJean-PRO** [comment]
The line the link points at is a fatal error apparently caused by the Apotheosis mod (line 2268).
As for JEI, it says nothing but it's not running at any point whenever the program tries to stop it, and that gets me confused. I will read it again tomorrow, as I just gave myself eye strain from forgetting about Ctrl+F.

**Comment by WenXin20** [comment]
Ah ok thanks. I wasn't sure if that error was related or not.

**Comment by ochotonida** [comment]
Definitely an issue on my side, although I'm still trying to figure out what's causing it

**Comment by ochotonida** [comment]
I've uploaded a patch that should fix the issue

**Comment by WenXin20** [comment]
Thanks!
