### ISSUE TITLE
There is a conflict between SAR and ExtraDelight

### ISSUE THREAD

**Issue by waliewa** [ochotonida/some-assembly-required#41]
Hello, I noticed a conflict between [SAR] Some Assembly Required and another mod {ExtraDelight}. Both can obtain bread slices by cutting bread, but the obtained items are not interchangeable and I am currently unable to obtain bread slices from SAR. So, could you please solve this problem? It would be best to merge the two types of bread slices, thank you very much!
![V(CVDN{{7WW NL7N8VV2 HU](https://github.com/ochotonida/some-assembly-required/assets/142482531/76d344b0-7b63-4f8c-a258-73c802466c2c)
![L@8Y(~HI(J050(WTH0VLB I](https://github.com/ochotonida/some-assembly-required/assets/142482531/075a5647-203d-4df4-b027-1032d6e8b9af)

**Comment by ochotonida** [comment]
Merging items isn't a thing, unfortunately. The best you can do is is using tags to make the items interchangeable and disable one of the recipes. I usually don't like disabling recipes or hiding items conditionally based on whether some other mod is loaded though, since this can be confusing for some users.

Some Assembly Required already uses the `forge:bread_slices` tag to check whether an item can be used as bread on a sandwich. Extra Delights also uses a tag, `forge:bread/sliced`, but since we're using different tags the items aren't interchangeable.

I think this is an issue that should be addressed by Extra Delights rather than Some Assembly Required, since the tag used by Extra Delights violates Forge's naming conventions for hierarchical tags. The name of the `forge:bread/sliced` tag implies that sliced bread is also part of the `forge:bread` tag. That doesn't appear to be the case or the intention though.
